---
# tasks file for freeradius (CentOS specific)


- name: Enable CRB repo
  become: yes
  yum_repository:
    name: crb
    file: /etc/yum.repos.d/centos.repo
    metalink: https://mirrors.centos.org/metalink?repo=centos-crb-$stream&arch=$basearch&protocol=https,http
    description: CentOS Stream $releasever - CRB
    enabled: true

- name: Install FreeRADIUS packages
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ freeradius_packages }}"
  tags:
    - freeradius
