---
# tasks file for freeradius (CentOS specific)


- name: Install FreeRADIUS packages
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ freeradius_packages }}"
  tags:
    - freeradius
